/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-17 12:53:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Project.View.NationalInfo;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Mongoliashow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>몽골 여행 정보</title>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: \"Noto Sans KR\", Arial, sans-serif;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .header {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 600px;\r\n");
      out.write("        background-image: url('../../assets/NationInfo/Mongolia/M0.png');\r\n");
      out.write("        background-size: cover;\r\n");
      out.write("        background-position: center;\r\n");
      out.write("    }\r\n");
      out.write("    .content {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        margin: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .left {\r\n");
      out.write("        width: 70%;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .right {\r\n");
      out.write("        width: 30%;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    h1, h2 {\r\n");
      out.write("        color: #333;\r\n");
      out.write("    }\r\n");
      out.write("    .list-view {\r\n");
      out.write("        list-style: none;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .list-view li {\r\n");
      out.write("        background: #f4f4f9;\r\n");
      out.write("        margin: 10px 0;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        border: 1px solid #ddd;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    .list-view img {\r\n");
      out.write("        width: 40%;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        margin: 0 auto 10px auto;\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("    .list-view span {\r\n");
      out.write("        display: block;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("        word-break: break-word;\r\n");
      out.write("    }\r\n");
      out.write("    .tourist-info {\r\n");
      out.write("        background: #f4f4f9;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border: 1px solid #ddd;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .tourist-info img {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"header\"></div>\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("        <div class=\"left\">\r\n");
      out.write("            <h1>몽골</h1>\r\n");
      out.write("            <h2>문화적 특성</h2>\r\n");
      out.write("            <ul class=\"list-view\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h3>개요</h3>\r\n");
      out.write("                    <img src=\"../../assets/NationInfo/Mongolia/MongoliaFlag.png\" alt=\"몽골 개요\">\r\n");
      out.write("                    <h4>수도: 울란바토르</h4>\r\n");
      out.write("                    <span>\r\n");
      out.write("                    &nbsp 몽골은 동아시아와 중앙아시아에 걸쳐 있는 내륙 국가로, 울란바토르를 수도로 합니다. 몽골은 광활한 초원과 사막, 산맥 등 다양한 자연 경관으로 유명하며, 유목민의 전통을 지키고 있는 나라입니다.<br><br>\r\n");
      out.write("                    \r\n");
      out.write("                    &nbsp 몽골은 고대 몽골 제국의 중심지였으며, 징기스칸의 후예로서 강력한 역사적 유산을 보유하고 있습니다. 오늘날 몽골은 전통과 현대가 조화를 이루며 발전하고 있습니다.\r\n");
      out.write("                    </span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h3>전통 문화</h3>\r\n");
      out.write("                    <img src=\"../../assets/NationInfo/Mongolia/M1.jpg\" alt=\"몽골 전통 문화\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                    &nbsp 몽골의 전통 문화는 유목 생활과 깊이 연관되어 있습니다. 몽골인들은 게르라는 전통적인 천막에서 생활하며, 말, 양, 소, 낙타 등의 가축을 키웁니다. 몽골의 전통 음악과 춤, 공예품 등은 유목민의 생활 방식을 반영하고 있습니다.<br><br>\r\n");
      out.write("                    \r\n");
      out.write("                    &nbsp 또한, 몽골은 불교가 주된 종교로 자리잡고 있으며, 불교 사원과 관련 의식도 중요한 문화 요소입니다.\r\n");
      out.write("                    </span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h3>식 문화</h3>\r\n");
      out.write("                    <img src=\"../../assets/NationInfo/Mongolia/M2.jpg\" alt=\"몽골 음식 문화\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                    &nbsp 몽골의 음식 문화는 유목 생활과 밀접한 관계가 있습니다. 대표적인 음식으로는 보즈, 호쇼르, 수테 차이 등이 있습니다. 보즈는 만두와 비슷한 음식으로, 양고기나 소고기로 만든 속을 채운 반죽을 찌거나 구워서 만듭니다.<br><br>\r\n");
      out.write("                    \r\n");
      out.write("                    &nbsp 호쇼르는 고기와 양파로 속을 채운 튀긴 만두로, 매우 인기 있는 길거리 음식입니다. 수테 차이는 차와 우유를 섞어 만든 음료로, 몽골 사람들이 즐겨 마시는 전통 음료입니다.\r\n");
      out.write("                    </span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h3>건축</h3>\r\n");
      out.write("                    <img src=\"../../assets/NationInfo/Mongolia/M3.png\" alt=\"몽골 건축\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                    &nbsp 몽골의 건축은 유목민의 전통적인 이동식 가옥인 게르가 가장 대표적입니다. 게르는 원형의 천막 구조로, 쉽게 이동하고 설치할 수 있어 유목 생활에 최적화된 건축물입니다.<br><br>\r\n");
      out.write("                    \r\n");
      out.write("                    &nbsp 또한, 몽골에는 다양한 불교 사원이 있으며, 라마교 사원의 독특한 건축 양식도 중요한 문화 자산입니다. 현대 몽골의 도시에서는 전통과 현대가 조화를 이루는 다양한 건축물을 볼 수 있습니다.\r\n");
      out.write("                    </span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h3>현대 대중문화</h3>\r\n");
      out.write("                    <img src=\"../../assets/NationInfo/Mongolia/M4.jpg\" alt=\"몽골 대중 문화\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                    &nbsp 몽골의 현대 대중문화는 전통과 현대가 혼합된 독특한 모습을 보입니다. 몽골의 음악, 영화, 패션 등 다양한 분야에서 현대적인 요소와 전통적인 요소가 조화를 이루고 있습니다.<br><br>\r\n");
      out.write("                    \r\n");
      out.write("                    &nbsp 몽골의 팝 음악과 현대 미술은 점차 국제적인 관심을 받고 있으며, 특히 젊은 세대 사이에서 큰 인기를 끌고 있습니다. 또한, 전통적인 스포츠인 나담 축제는 몽골의 중요한 문화 행사로 자리잡고 있습니다.\r\n");
      out.write("                    </span>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"right\">\r\n");
      out.write("        <h2>관광지</h2>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>고비 사막</h3>\r\n");
      out.write("            <img src=\"../../assets/NationInfo/Mongolia/M5.jpg\" alt=\"고비 사막\">\r\n");
      out.write("            <p>고비 사막은 몽골 남부에 위치한 광활한 사막으로, 독특한 풍경과 모험을 즐길 수 있는 관광지입니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>테를지 국립공원</h3>\r\n");
      out.write("            <img src=\"../../assets/NationInfo/Mongolia/M6.jpg\" alt=\"테를지 국립공원\">\r\n");
      out.write("            <p>테를지 국립공원은 몽골의 자연 경관을 즐길 수 있는 곳으로, 하이킹, 승마, 캠핑 등 다양한 활동을 할 수 있습니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>울란바토르의 간단 사원</h3>\r\n");
      out.write("            <img src=\"../../assets/NationInfo/Mongolia/M7.jpg\" alt=\"간단 사원\">\r\n");
      out.write("            <p>간단 사원은 울란바토르에 위치한 불교 사원으로, 몽골의 종교적 역사와 문화를 엿볼 수 있는 중요한 장소입니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>오르혼 계곡</h3>\r\n");
      out.write("            <img src=\"../../assets/NationInfo/Mongolia/M8.jpg\" alt=\"오르혼 계곡\">\r\n");
      out.write("            <p>오르혼 계곡은 몽골의 역사적 유적지로, 유네스코 세계유산으로 지정되어 있습니다. 이곳에서는 고대 몽골 제국의 유산을 감상할 수 있습니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>카라코룸</h3>\r\n");
      out.write("            <img src=\"../../assets/NationInfo/Mongolia/M9.png\" alt=\"카라코룸\">\r\n");
      out.write("            <p>카라코룸은 고대 몽골 제국의 수도였던 도시로, 역사적 유적과 문화적 유산을 탐방할 수 있는 곳입니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>나담 축제</h3>\r\n");
      out.write("            <img src=\"../../assets/NationInfo/Mongolia/M10.png\" alt=\"나담 축제\">\r\n");
      out.write("            <p>나담 축제는 몽골의 전통 스포츠와 문화를 체험할 수 있는 행사로, 씨름, 활쏘기, 말타기 등의 경기가 펼쳐집니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
