/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-17 14:33:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Project.View.NationalInfo;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Taiwanshow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>대만 여행 정보</title>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: \"Noto Sans KR\", Arial, sans-serif;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .header {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 600px;\r\n");
      out.write("        background-image: url('../../assets/NationInfo/Taiwan/T0.png');\r\n");
      out.write("        background-size: cover;\r\n");
      out.write("        background-position: center;\r\n");
      out.write("    }\r\n");
      out.write("    .content {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        margin: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .left {\r\n");
      out.write("        width: 70%;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .right {\r\n");
      out.write("        width: 30%;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    h1, h2 {\r\n");
      out.write("        color: #333;\r\n");
      out.write("    }\r\n");
      out.write("    .list-view {\r\n");
      out.write("        list-style: none;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .list-view li {\r\n");
      out.write("        background: #f4f4f9;\r\n");
      out.write("        margin: 10px 0;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        border: 1px solid #ddd;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    .list-view img {\r\n");
      out.write("        width: 40%;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        margin: 0 auto 10px auto;\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("    .list-view span {\r\n");
      out.write("        display: block;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("        word-break: break-word;\r\n");
      out.write("    }\r\n");
      out.write("    .tourist-info {\r\n");
      out.write("        background: #f4f4f9;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border: 1px solid #ddd;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .tourist-info img {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"header\"></div>\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("        <div class=\"left\">\r\n");
      out.write("            <h1>대만</h1>\r\n");
      out.write("            <h2>문화적 특성</h2>\r\n");
      out.write("            <ul class=\"list-view\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h3>개요</h3>\r\n");
      out.write("                    <img src=\"../../assets/NationInfo/Taiwan/TaiwanFlag.png\" alt=\"대만 개요\">\r\n");
      out.write("                    <h4>수도: 타이베이</h4>\r\n");
      out.write("                    <span>\r\n");
      out.write("                    &nbsp 대만은 동아시아에 위치한 섬나라로, 타이베이를 수도로 합니다. 대만은 풍부한 역사와 문화, 아름다운 자연 경관으로 유명합니다. 대만은 현대적인 도시와 전통 문화가 어우러진 독특한 매력을 지닌 나라입니다.<br><br>\r\n");
      out.write("                    \r\n");
      out.write("                    &nbsp 대만은 민주주의를 기반으로 한 공화국으로, 활발한 경제 활동과 자유로운 사회 분위기를 자랑합니다. 전통적인 문화와 현대적인 발전이 공존하는 곳으로, 다양한 문화적 영향을 받아온 대만은 그만의 독특한 문화를 형성하였습니다.\r\n");
      out.write("                    </span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h3>전통 문화</h3>\r\n");
      out.write("                    <img src=\"../../assets/NationInfo/Taiwan/T1.png\" alt=\"대만 전통 문화\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                    &nbsp 대만의 전통 문화는 중국의 영향을 많이 받았으며, 민속 예술, 전통 축제, 의식 등 다양한 면에서 중국의 전통을 유지하고 있습니다. 대만의 전통 명절로는 춘절, 중추절, 단오절 등이 있으며, 이 기간 동안 다양한 전통 행사가 열립니다.<br><br>\r\n");
      out.write("                    \r\n");
      out.write("                    &nbsp 또한, 대만은 다양한 민족과 문화가 공존하는 곳으로, 원주민 문화와 외국 문화가 어우러져 독특한 문화적 풍경을 이루고 있습니다.\r\n");
      out.write("                    </span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h3>식 문화</h3>\r\n");
      out.write("                    <img src=\"../../assets/NationInfo/Taiwan/T2.png\" alt=\"대만 음식 문화\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                    &nbsp 대만의 음식 문화는 매우 다양하며, 신선한 재료와 독특한 조리법이 특징입니다. 대표적인 음식으로는 소룡포, 누가차, 타이완 소고기 국수, 펑리수가 있습니다.<br><br>\r\n");
      out.write("                    \r\n");
      out.write("                    &nbsp 대만의 야시장 문화도 유명하며, 야시장에서 다양한 길거리 음식을 맛볼 수 있습니다. 대만의 음식은 중국 요리의 영향을 많이 받았으나, 대만만의 독특한 맛을 자랑합니다.\r\n");
      out.write("                    </span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h3>건축</h3>\r\n");
      out.write("                    <img src=\"../../assets/NationInfo/Taiwan/T3.jpg\" alt=\"대만 건축\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                    &nbsp 대만의 건축은 전통적인 중국식 건축물과 현대적인 건축물이 조화를 이루고 있습니다. 대표적인 건축물로는 타이페이 101, 타이베이의 용산사, 중정기념당 등이 있습니다.<br><br>\r\n");
      out.write("                    \r\n");
      out.write("                    &nbsp 또한, 대만의 전통 가옥인 삼합원과 같은 건축 양식은 대만의 역사와 문화를 잘 반영하고 있습니다. 최근에는 현대적이고 창의적인 건축물도 많이 생겨나고 있습니다.\r\n");
      out.write("                    </span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h3>현대 대중문화</h3>\r\n");
      out.write("                    <img src=\"../../assets/NationInfo/Taiwan/T4.jpg\" alt=\"대만 대중 문화\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                    &nbsp 대만의 현대 대중문화는 음악, 영화, 드라마 등 다양한 분야에서 큰 인기를 끌고 있습니다. 대만의 음악은 중국어권을 넘어 전 세계에서 사랑받고 있으며, 대만 영화와 드라마도 많은 팬층을 보유하고 있습니다.<br><br>\r\n");
      out.write("                    \r\n");
      out.write("                    &nbsp 특히, 대만의 드라마는 아시아 전역에서 큰 인기를 얻고 있으며, 대만의 아이돌 그룹과 가수들도 국제적인 성공을 거두고 있습니다.\r\n");
      out.write("                    </span>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"right\">\r\n");
      out.write("        <h2>관광지</h2>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>타이페이 101</h3>\r\n");
      out.write("            <img src=\"../../assets/NationInfo/Taiwan/T5.png\" alt=\"타이페이 101\">\r\n");
      out.write("            <p>타이페이 101은 대만의 대표적인 랜드마크로, 고층 빌딩의 전망대에서 타이페이 시내를 한눈에 볼 수 있습니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>일월담</h3>\r\n");
      out.write("            <img src=\"../../assets/NationInfo/Taiwan/T6.png\" alt=\"일월담\">\r\n");
      out.write("            <p>일월담은 대만 중부에 위치한 아름다운 호수로, 자연 경관과 호수 주변의 다양한 액티비티를 즐길 수 있습니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>타이난의 고궁박물원</h3>\r\n");
      out.write("            <img src=\"../../assets/NationInfo/Taiwan/T7.png\" alt=\"고궁박물원\">\r\n");
      out.write("            <p>타이난의 고궁박물원은 대만의 역사와 문화를 한눈에 볼 수 있는 중요한 문화유산입니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>지우펀</h3>\r\n");
      out.write("            <img src=\"../../assets/NationInfo/Taiwan/T8.png\" alt=\"지우펀\">\r\n");
      out.write("            <p>지우펀은 대만 북부에 위치한 작은 마을로, 옛날 채광 산업의 중심지였으며, 현재는 독특한 거리 풍경과 맛있는 먹거리로 유명한 관광지입니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>타로코 협곡</h3>\r\n");
      out.write("            <img src=\"../../assets/NationInfo/Taiwan/T9.jpg\" alt=\"타로코 협곡\">\r\n");
      out.write("            <p>타로코 협곡은 대만 동부에 위치한 대자연의 경이로움을 느낄 수 있는 장소로, 웅장한 절경을 감상할 수 있습니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>중정기념당</h3>\r\n");
      out.write("            <img src=\"../../assets/NationInfo/Taiwan/T10.png\" alt=\"중정기념당\">\r\n");
      out.write("            <p>중정기념당은 타이베이에 위치한 역사적인 건축물로, 대만의 정치적 역사를 이해할 수 있는 중요한 장소입니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
