/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-08 19:23:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Project;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Chinashow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>중국 여행 정보</title>\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: Arial, sans-serif;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .header {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 600px;\r\n");
      out.write("        background-image: url('assets/China.png');\r\n");
      out.write("        background-size: cover;\r\n");
      out.write("        background-position: center;\r\n");
      out.write("    }\r\n");
      out.write("    .content {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        margin: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .left {\r\n");
      out.write("        width: 70%;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .right {\r\n");
      out.write("        width: 30%;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    h1, h2 {\r\n");
      out.write("        color: #333;\r\n");
      out.write("    }\r\n");
      out.write("    .list-view {\r\n");
      out.write("        list-style: none;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .list-view li {\r\n");
      out.write("        background: #f4f4f9;\r\n");
      out.write("        margin: 10px 0;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        border: 1px solid #ddd;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    .list-view img {\r\n");
      out.write("        width: 40%;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        margin: 0 auto 10px auto;\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("    .list-view span {\r\n");
      out.write("        display: block;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("        word-break: break-word;\r\n");
      out.write("    }\r\n");
      out.write("    .tourist-info {\r\n");
      out.write("        background: #f4f4f9;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border: 1px solid #ddd;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .tourist-info img {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"header\"></div>\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("        <div class=\"left\">\r\n");
      out.write("            <h1>중국</h1>\r\n");
      out.write("            <h2>문화적 특성</h2>\r\n");
      out.write("            <ul class=\"list-view\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h3>개요</h3>\r\n");
      out.write("                    <img src=\"assets/NationInfo/China/ChinaFlag.png\" alt=\"문화적 특성 1\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                    &nbsp 중국은 동아시아에 위치한 국가로, 세계에서 가장 인구가 많은 나라입니다. 수도는 베이징이며, 공식 명칭은 중화인민공화국입니다. 중국은 오랜 역사와 풍부한 문화유산을 자랑하며, 다양한 민족과 언어가 공존하는 다민족 국가입니다.<br><br>\r\n");
      out.write("                    \r\n");
      out.write("                    &nbsp 중국은 공산당 일당제 국가로, 1949년 중화인민공화국 건국 이후 사회주의 체제를 유지하고 있습니다. 최근에는 개혁개방 정책을 통해 경제 성장을 이루며 세계 경제에서 중요한 위치를 차지하고 있습니다.<br><br>\r\n");
      out.write("                    \r\n");
      out.write("                    &nbsp 중국의 문화는 유교, 도교, 불교 등의 전통적인 사상과 함께 현대적인 요소들이 결합되어 있습니다.\r\n");
      out.write("                    </span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h3>전통 문화</h3>\r\n");
      out.write("                    <img src=\"assets/ChinaCulture.png\" alt=\"문화적 특성 2\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                    &nbsp 중국의 전통 문화는 수천 년의 역사 속에서 발전해왔으며, 특히 문학, 예술, 철학 등이 중요한 역할을 해왔습니다. 중국의 전통적인 춤과 음악, 서예, 그림 등은 전 세계적으로 유명합니다.<br><br>\r\n");
      out.write("                    \r\n");
      out.write("                    &nbsp 중국의 전통 명절로는 춘절(설날), 중추절(추석), 단오절 등이 있으며, 이러한 명절 동안에는 가족들이 모여 다양한 전통 음식을 즐기고 풍습을 지킵니다.\r\n");
      out.write("                    </span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h3>식 문화</h3>\r\n");
      out.write("                    <img src=\"assets/ChinaFood.png\" alt=\"문화적 특성 3\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                    &nbsp 중국의 음식 문화는 매우 다양하며, 지역에 따라 독특한 요리가 많습니다. 대표적인 음식으로는 베이징의 베이징덕, 사천의 마라탕, 광둥의 딤섬 등이 있습니다.<br><br>\r\n");
      out.write("                    \r\n");
      out.write("                    &nbsp 중국의 식문화는 오랜 역사 속에서 발달해왔으며, 특히 다양한 조리법과 풍부한 재료를 사용한 요리가 많습니다. 중국의 음식은 색, 향, 맛의 조화를 중요시하며, 건강을 고려한 약선 요리도 발달해 있습니다.\r\n");
      out.write("                    </span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h3>건축</h3>\r\n");
      out.write("                    <img src=\"assets/ChinaArchitecture.png\" alt=\"문화적 특성 4\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                    &nbsp 중국의 건축은 오랜 역사와 전통을 반영한 다양한 양식을 가지고 있습니다. 대표적인 건축물로는 자금성, 만리장성, 천안문 광장 등이 있습니다.<br><br>\r\n");
      out.write("                    \r\n");
      out.write("                    &nbsp 또한, 중국의 전통 가옥인 사합원은 북경을 중심으로 한 북방 지역에서 많이 볼 수 있으며, 남방 지역에서는 민가, 토루 등이 대표적인 건축물입니다. 최근에는 현대적이고 독창적인 건축물도 많이 생겨나고 있습니다.\r\n");
      out.write("                    </span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h3>현대 대중문화</h3>\r\n");
      out.write("                    <img src=\"assets/ChinaPopCulture.png\" alt=\"문화적 특성 5\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                    &nbsp 중국의 현대 대중문화는 급속한 경제 발전과 함께 빠르게 변화하고 있습니다. 영화, 음악, 드라마 등 다양한 분야에서 중국의 대중문화가 전 세계적으로 인기를 끌고 있습니다.<br><br>\r\n");
      out.write("                    \r\n");
      out.write("                    &nbsp 특히, 중국의 영화 산업은 헐리우드와 함께 세계적인 규모를 자랑하며, 중국 내수 시장뿐만 아니라 해외 시장에서도 큰 성공을 거두고 있습니다. 또한, 중국의 음악과 패션도 많은 이들에게 영향을 미치고 있습니다.\r\n");
      out.write("                    </span>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"right\">\r\n");
      out.write("        <h2>관광지</h2>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>자금성</h3>\r\n");
      out.write("            <img src=\"assets/China1.jpg\" alt=\"자금성\">\r\n");
      out.write("            <p>자금성은 베이징에 위치한 중국의 대표적인 유적지로, 명나라와 청나라 시대의 황궁이었습니다. 웅장한 건축물과 역사적 유물이 가득한 곳입니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>만리장성</h3>\r\n");
      out.write("            <img src=\"assets/China2.jpg\" alt=\"만리장성\">\r\n");
      out.write("            <p>만리장성은 중국의 대표적인 역사 유적지로, 길이가 약 21,196km에 달하는 거대한 성벽입니다. 다양한 구간에서 아름다운 경관과 역사의 흔적을 감상할 수 있습니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>상하이 동방명주</h3>\r\n");
      out.write("            <img src=\"assets/China3.jpg\" alt=\"동방명주\">\r\n");
      out.write("            <p>상하이에 위치한 동방명주는 상하이의 대표적인 랜드마크로, 아름다운 야경과 전망대에서 바라보는 도심 전경이 유명합니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>시안 병마용</h3>\r\n");
      out.write("            <img src=\"assets/China4.jpg\" alt=\"병마용\">\r\n");
      out.write("            <p>시안에 위치한 병마용은 진시황의 무덤에서 발견된 수천 개의 병사와 말 모형으로, 고대 중국의 역사를 엿볼 수 있는 중요한 유적지입니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>구채구</h3>\r\n");
      out.write("            <img src=\"assets/China5.jpg\" alt=\"구채구\">\r\n");
      out.write("            <p>구채구는 중국 사천성에 위치한 자연 보호구역으로, 아름다운 호수와 폭포, 숲이 어우러진 천혜의 자연 경관을 자랑합니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>황산</h3>\r\n");
      out.write("            <img src=\"assets/China6.jpg\" alt=\"황산\">\r\n");
      out.write("            <p>황산은 중국 안후이성에 위치한 명산으로, 기암괴석과 운해, 고대 소나무로 유명합니다. 중국 전통 회화의 소재로 많이 사용되었습니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
