/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-09 14:11:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Project;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Japanshow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>일본 여행 정보</title>\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: Arial, sans-serif;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .header {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 600px;\r\n");
      out.write("        background-image: url('assets/NationInfo/Japan/J0.jpg');\r\n");
      out.write("        background-size: cover;\r\n");
      out.write("        background-position: center;\r\n");
      out.write("    }\r\n");
      out.write("    .content {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        margin: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .left {\r\n");
      out.write("        width: 70%;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .right {\r\n");
      out.write("        width: 30%;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    h1, h2 {\r\n");
      out.write("        color: #333;\r\n");
      out.write("    }\r\n");
      out.write("    .list-view {\r\n");
      out.write("        list-style: none;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .list-view li {\r\n");
      out.write("        background: #f4f4f9;\r\n");
      out.write("        margin: 10px 0;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        border: 1px solid #ddd;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    .list-view img {\r\n");
      out.write("        width: 40%;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        margin: 0 auto 10px auto;\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("    .list-view span {\r\n");
      out.write("        display: block;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("        word-break: break-word;\r\n");
      out.write("    }\r\n");
      out.write("    .tourist-info {\r\n");
      out.write("        background: #f4f4f9;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border: 1px solid #ddd;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .tourist-info img {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"header\"></div>\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("        <div class=\"left\">\r\n");
      out.write("            <h1>일본</h1>\r\n");
      out.write("            <h2>문화적 특성</h2>\r\n");
      out.write("            <ul class=\"list-view\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h3>개요</h3>\r\n");
      out.write("                    <img src=\"assets/NationInfo/Japan/JapanFlag.png\" alt=\"문화적 특성 1\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                    &nbsp 일본은 동아시아에 위치한 섬나라로, 도쿄를 수도로 합니다. 일본은 오래된 역사와 전통을 지닌 나라로, 현대적인 도시와 고대 유적이 공존하는 곳입니다.<br><br>\r\n");
      out.write("                    \r\n");
      out.write("                    &nbsp 일본은 헌법상 입헌군주제와 의원내각제를 채택하고 있으며, 천황이 상징적인 국가원수로 자리하고 있습니다. 일본은 세계에서 세 번째로 큰 경제 대국으로, 기술과 문화, 예술 등 다양한 분야에서 세계적인 영향력을 발휘하고 있습니다.<br><br>\r\n");
      out.write("                    \r\n");
      out.write("                    &nbsp 일본의 문화는 섬나라이기 때문에 독특한 발전 과정을 거쳐왔으며, 전통과 현대가 조화를 이루고 있습니다.\r\n");
      out.write("                    </span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h3>전통 문화</h3>\r\n");
      out.write("                    <img src=\"assets/NationInfo/Japan/J1.jpeg\" alt=\"문화적 특성 2\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                    &nbsp 일본의 전통 문화는 긴 역사 속에서 발전해왔으며, 특히 예술, 문학, 종교 등의 분야에서 중요한 역할을 해왔습니다. 일본의 전통적인 춤과 음악, 다도, 서예 등은 전 세계적으로 유명합니다.<br><br>\r\n");
      out.write("                    \r\n");
      out.write("                    &nbsp 일본의 전통 명절로는 오봉, 신년, 히나마츠리 등이 있으며, 이러한 명절 동안에는 가족들이 모여 전통 음식을 즐기고 전통 의상을 입는 등의 풍습을 지킵니다.\r\n");
      out.write("                    </span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h3>식 문화</h3>\r\n");
      out.write("                    <img src=\"assets/NationInfo/Japan/J2.png\" alt=\"문화적 특성 3\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                    &nbsp 일본의 음식 문화는 매우 다양하며, 신선한 재료와 정교한 조리법이 특징입니다. 대표적인 음식으로는 스시, 사시미, 라멘, 템푸라 등이 있습니다.<br><br>\r\n");
      out.write("                    \r\n");
      out.write("                    &nbsp 일본의 식문화는 섬나라의 특성상 해산물을 많이 사용하며, 각 지역마다 독특한 요리가 있습니다. 또한, 일본의 전통 음식을 제공하는 이자카야, 오마카세 등의 레스토랑도 유명합니다.\r\n");
      out.write("                    </span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h3>건축</h3>\r\n");
      out.write("                    <img src=\"assets/NationInfo/Japan/J3.png\" alt=\"문화적 특성 4\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                    &nbsp 일본의 건축은 전통적인 목조 건축물과 현대적인 건축물이 조화를 이루고 있습니다. 대표적인 건축물로는 도쿄 타워, 교토의 금각사, 오사카 성 등이 있습니다.<br><br>\r\n");
      out.write("                    \r\n");
      out.write("                    &nbsp 또한, 일본의 전통 가옥인 마치야와 신사의 건축 양식은 일본의 문화와 역사를 반영하고 있습니다. 최근에는 현대적이고 독창적인 건축물도 많이 생겨나고 있습니다.\r\n");
      out.write("                    </span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h3>현대 대중문화</h3>\r\n");
      out.write("                    <img src=\"assets/NationInfo/Japan/J4.jpg\" alt=\"문화적 특성 5\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                    &nbsp 일본의 현대 대중문화는 애니메이션, 만화, 게임 등 다양한 분야에서 전 세계적으로 큰 인기를 끌고 있습니다. 일본의 영화, 음악, 드라마도 많은 팬층을 보유하고 있습니다.<br><br>\r\n");
      out.write("                    \r\n");
      out.write("                    &nbsp 특히, 일본의 애니메이션과 만화는 독특한 예술성과 이야기로 세계 각지에서 사랑받고 있으며, 일본의 게임 산업도 글로벌 시장에서 큰 영향력을 발휘하고 있습니다.\r\n");
      out.write("                    </span>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"right\">\r\n");
      out.write("        <h2>관광지</h2>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>도쿄 타워</h3>\r\n");
      out.write("            <img src=\"assets/NationInfo/Japan/J5.jpg\" alt=\"도쿄 타워\">\r\n");
      out.write("            <p>도쿄 타워는 일본 도쿄의 랜드마크로, 아름다운 야경과 도쿄 시내 전경을 감상할 수 있는 전망대가 있습니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>후지산</h3>\r\n");
      out.write("            <img src=\"assets/NationInfo/Japan/J6.jpg\" alt=\"후지산\">\r\n");
      out.write("            <p>후지산은 일본의 상징적인 산으로, 등산과 함께 아름다운 자연 경관을 즐길 수 있는 인기 관광지입니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>교토의 금각사</h3>\r\n");
      out.write("            <img src=\"assets/NationInfo/Japan/J7.jpg\" alt=\"금각사\">\r\n");
      out.write("            <p>교토에 위치한 금각사는 일본의 전통 건축 양식을 잘 보여주는 유서 깊은 사찰입니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>오사카 성</h3>\r\n");
      out.write("            <img src=\"assets/NationInfo/Japan/J8.jpg\" alt=\"오사카 성\">\r\n");
      out.write("            <p>오사카 성은 일본의 대표적인 역사 유적지로, 아름다운 성곽과 함께 주변 공원이 인상적입니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>나라의 사슴 공원</h3>\r\n");
      out.write("            <img src=\"assets/NationInfo/Japan/J9.png\" alt=\"사슴 공원\">\r\n");
      out.write("            <p>나라의 사슴 공원은 자유롭게 돌아다니는 사슴들과 함께할 수 있는 독특한 관광지입니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>히로시마 평화 기념 공원</h3>\r\n");
      out.write("            <img src=\"assets/NationInfo/Japan/J10.jpg\" alt=\"평화 기념 공원\">\r\n");
      out.write("            <p>히로시마 평화 기념 공원은 원자 폭탄 피해를 기억하고 평화를 기원하는 장소로, 역사적 의미가 깊은 곳입니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
