/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-09 15:17:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Project;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Koreashow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>대한민국 여행 정보</title>\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: Arial, sans-serif;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .header {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 600px;\r\n");
      out.write("        background-image: url('assets/NationInfo/Korea/Korea.png');\r\n");
      out.write("        background-size: cover;\r\n");
      out.write("        background-position: center;\r\n");
      out.write("    }\r\n");
      out.write("    .content {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        margin: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .left {\r\n");
      out.write("        width: 70%;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .right {\r\n");
      out.write("        width: 30%;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    h1, h2 {\r\n");
      out.write("        color: #333;\r\n");
      out.write("    }\r\n");
      out.write("    .list-view {\r\n");
      out.write("        list-style: none;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .list-view li {\r\n");
      out.write("        background: #f4f4f9;\r\n");
      out.write("        margin: 10px 0;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        border: 1px solid #ddd;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    .list-view img {\r\n");
      out.write("        width: 40%; /* 이미지 너비를 50%로 설정 */\r\n");
      out.write("        height: auto;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        margin: 0 auto 10px auto; /* 이미지 중앙 정렬 및 하단 여백 추가 */\r\n");
      out.write("        display: block; /* 블록 레벨 요소로 설정 */\r\n");
      out.write("    }\r\n");
      out.write("    .list-view span {\r\n");
      out.write("        display: block;\r\n");
      out.write("        text-align: left; /* 텍스트 좌측 정렬 */\r\n");
      out.write("        word-break: break-word; /* 긴 단어가 div를 넘어가지 않도록 설정 */\r\n");
      out.write("    }\r\n");
      out.write("    .tourist-info {\r\n");
      out.write("        background: #f4f4f9;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border: 1px solid #ddd;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    .tourist-info {\r\n");
      out.write("        background: #f4f4f9;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border: 1px solid #ddd;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        margin-bottom: 20px; /* 관광지 정보 섹션 간 여백 추가 */\r\n");
      out.write("        text-align: center; /* 텍스트를 가운데 정렬 */\r\n");
      out.write("    }\r\n");
      out.write("    .tourist-info img {\r\n");
      out.write("        width: 100%; /* 이미지 너비를 100%로 설정 */\r\n");
      out.write("        height: auto;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        margin-bottom: 10px; /* 하단 여백 추가 */\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"header\"></div>\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("        <div class=\"left\">\r\n");
      out.write("            <h1>대한민국</h1>\r\n");
      out.write("            <h2>문화적 특성</h2>\r\n");
      out.write("            <ul class=\"list-view\">\r\n");
      out.write("                <li>\r\n");
      out.write("                	<h3>개요</h3>\r\n");
      out.write("                    <img src=\"assets/NationInfo/Korea/KoreaFlag.png\" alt=\"문화적 특성 1\">\r\n");
      out.write("                    <h4>수도: 서울</h4>\r\n");
      out.write("                    <span>                 \r\n");
      out.write("                    &nbsp 오늘날 한국의 문화는 국제적인 명성을 얻었으며, 흔히 말하는 소프트 파워로 따지자면 한국은 슈퍼 파워로 분류된다. 국제적으로 여기에 해당되는 국가는 미국, 영국, 프랑스, 독일, 이탈리아, 일본 등 소수 문화강국들 뿐이다                 \r\n");
      out.write("                    대한민국은 동아시아의 한반도에 위치한 대통령제 공화국이다. 서쪽으로 중화인민공화국, 동쪽으로 일본에 접해 있으며, 북쪽으로 조선민주주의인민공화국과 닿아 있다. 수도이자 최대 도시는 서울특별시이다.<br><br>\r\n");
      out.write("					\r\n");
      out.write("					&nbsp 한반도는 제2차 세계 대전에서 일본이 패전한 이후 분단되었으며, 1948년에 대한민국이 수립되었다. 대한민국은 이후 미국과의 동맹을 유지하며 성공적으로 민주주의를 발전시켰다.<br><br>\r\n");
      out.write("				\r\n");
      out.write("					&nbsp 대한민국은 1960년대부터 1980년대까지 세계에서 가장 빠른 경제 성장을 이룬 국가들 중 하나이며 선진국으로 여겨지고 있다. \r\n");
      out.write("					대한민국은 G20과 경제협력개발기구의 회원국이다. 조선민주주의인민공화국과의 긴장 상태로 인해, 대한민국은 세계 6위의 군사 대국이며 세계 10위의 국방비를 지출하고 있다.<br><br>\r\n");
      out.write("\r\n");
      out.write("					&nbsp 대한민국의 산업은 과학과 기술 분야에 집중되어 있다. \r\n");
      out.write("					기반 시설과 대규모 가족 기업인 재벌이 주도하는 반도체, 액정 디스플레이, 컴퓨터, 휴대 전화 등의 정보기술이 발달해 있다.\r\n");
      out.write("					대한민국의 경제는 건설, 공학, 기계, 로봇공학, 생명공학기술, 석유화학 분야에 집중되어 있다.</span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                	<h3>전통 문화</h3>\r\n");
      out.write("                    <img src=\"assets/NationInfo/Korea/Kgame.png\" alt=\"문화적 특성 2\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                    &nbsp 민속놀이(韓國의 民俗놀이)는 한국의 전통적인 놀이를 말한다. \r\n");
      out.write("					예로부터 주로 서민층에서 명절이나 혹은 특별한 일이 있을 경우에 예식의 하나로서 여흥을 돋구고자, 또는 어린이들 사이에서 교육과 유희를 위해 행하여졌다. \r\n");
      out.write("					각각의 놀이의 유래는 민속놀이는 남녀노소가 함께 즐길 수 있는 놀이가 있는가 하면, 어른들만이 하는 놀이, 소년, 소녀들끼리 하는 놀이, 여자들 간에 혹은 남자들 간에만 하는 놀이가 있다. \r\n");
      out.write("					놀이의 성격을 벗어나 힘과 기술을 겨루는 스포츠로 발전한 것으로는 씨름을 꼽을 수 있다.<br><br>\r\n");
      out.write("\r\n");
      out.write("					&nbsp 바둑은 두 명이 흑과 백의 돌을 판 위에 번갈아 놓으며 집을 차지하는 것을 겨루는 놀이이다. \r\n");
      out.write("					가로와 세로가 19줄이 그어진 바둑판 위의 각 교차점(모두 361개)에 돌을 두며, 공격과 수비를 하는 전략 게임이기도 하다. \r\n");
      out.write("					대한민국, 중화인민공화국, 중화민국, 일본 등 동아시아 국가들 사이에서 대중적으로 행해지며, 나라마다 조금씩 다른 규칙을 채용하고 있다. \r\n");
      out.write("					바둑은 고대 중국에서 기원하였지만, 그 기원이 언제인지는 명확하지 않다. 한국에서는 20세기 초까지 고유의 규칙을 사용하는 순장(巡將)바둑이 성행하였으나 해방 후 일본으로부터 현대 바둑이 유입되어 현대에 들어 순장바둑을 두는 사람들은 크게 줄어들었다.<br><br>\r\n");
      out.write("\r\n");
      out.write("					&nbsp 장기 (將棋)란 청과 홍(또는 초와 한) 두 편으로 나뉘어 각 16개의 기물을 가지고 군대를 지휘하는 총사령관의 입장에서 작전을 구상, 수행하여 상대편의 왕을 잡는 추상 전략 보드 게임이다. \r\n");
      out.write("					대한민국, 조선민주주의인민공화국, 중국(특히 연변 조선족 자치주), 일본 등 각국에서 주로 한민족들이 즐긴다. \r\n");
      out.write("					중국 장기가 한국의 삼국 시대 초기인 한사군(漢四郡) 시절에 수많은 한인(漢人)이 이주해 오면서 장기를 퍼뜨렸다는 설이 가장 지배적이다. \r\n");
      out.write("					한국인의 취향에 맞춰 개량하여 지금의 장기로 발전시켰다고 한다. 장기에 관한 문헌으로는 고사서(古史書)인 김부식의 《삼국사기》에 장기에 대한 기록이 최초로 등장한다.<br><br></span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                	<h3>식 문화</h3>\r\n");
      out.write("                    <img src=\"assets/NationInfo/Korea/Kfood.jpg\" alt=\"문화적 특성 3\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                    	&nbsp 한국 요리 (韓國料理)는 한국의 전통 음식을 뜻한다. 복잡한 궁중 요리에서부터 지방의 특색 요리와 현대의 퓨전 요리에 이르기까지 재료와 조리법이 매우 다양하다. \r\n");
      out.write("						전통적인 한국 정식은 밥, 국, 김치와 함께 나오는 많은 반찬들로 이루어진다. \r\n");
      out.write("						한국 음식은 보통 참기름, 된장, 간장, 소금, 마늘, 생강, 그리고 고추장 등으로 맛을 낸다. \r\n");
      out.write("						식단은 계절별로 다양한데, 전통적으로 겨울 동안에는 장독에 저장된 김치와 그 밖에 절인 채소들에 많이 의존했다.<br><br>\r\n");
      out.write("\r\n");
      out.write("						&nbsp 한국은 기후와 풍토가 농사에 적합하여 일찍이 신석기시대 후에 잡곡 농사로 농업이 시작되었고, 그 후 벼농사가 전파되었다. \r\n");
      out.write("						이후 곡물은 한국 음식문화의 중심이 되었고, 삼국시대 후기부터 밥과 반찬으로 주식, 부식을 분리한 한국 고유의 일상식 형태가 형성되었다. \r\n");
      out.write("						밥, 죽, 떡, 국수, 만두, 수제비, 술 등의 곡물 음식이 발달하였고 콩으로 메주를 쑤어 장을 담그는 발효 음식도 발달하였다. \r\n");
      out.write("						재배 채소뿐 아니라, 산야에 자생하는 산나물, 들나물 등 채소의 종류가 다양하여 생채, 쌈, 나물, 김치로 만들어 식탁을 계절에 따라 변화있게 차릴 수 있었다. \r\n");
      out.write("						예로부터 약식동원(藥食同原, 약과 음식은 그 근본이 같다)의 식관념 속에 약으로 쓰이는 재료가 음식의 조리에 많이 이용되고 있다.<br><br>\r\n");
      out.write("\r\n");
      out.write("						&nbsp 한국인의 일상식은 밥을 주식으로 하고, 여러 가지 반찬을 곁들여 먹는 식사 형태이다. \r\n");
      out.write("						주식은 쌀만으로 지은 쌀밥과 조, 보리, 콩, 팥 등의 잡곡을 섞어 지은 잡곡밥을 기본으로 한다. \r\n");
      out.write("						부식은 국이나 찌개, 김치와 장류를 기본으로 하고, 육류, 어패류, 채소류, 해조류 등을 이용해서 반찬을 만들었다. \r\n");
      out.write("						이렇게 밥과 반찬을 같이 먹는 식사 형태는 여러 가지 식품을 골고루 섭취함으로써 영양의 균형을 상호 보완시켜주는 합리적인 식사 형식이다.<br><br>\r\n");
      out.write("\r\n");
      out.write("						&nbsp 주식으로는 밥, 죽, 국수, 만두, 떡국, 수제비 등이 있고, 부식으로는 국, 찌개, 구이, 전, 조림, 볶음, 편육, 나물, 생채, 젓갈, 포, 장아찌, 찜, 전골, 김치 등 가지수가 많다. \r\n");
      out.write("						이러한 음식 외에 떡, 한과, 엿, 화채, 차, 술 등의 음식도 다양하다. 또 저장 발효 식품인 장류, 젓갈, 김치 등이 다양하게 발달하였다.<br><br>  \r\n");
      out.write("                    </span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                	<h3>건축</h3>\r\n");
      out.write("                    <img src=\"assets/NationInfo/Korea/Kstruct.png\" alt=\"문화적 특성 3\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                    	&nbsp 한국의 건축 기술에 비해 발달되고 효율적인 미국 모델은 전통적인 건물, 건축 기법, 현지 자재 사용 및 현지 토속 스타일을 유지하는 토목 및 농촌 건축과 함께 중요한 한국의 새로운 건물에 중요한 영향을 미쳤다. \r\n");
      out.write("						착취적 식민화와 내전으로 황폐해진 나라를 재건해야 한다는 실용적인 필요성으로 인해 특별한 스타일이 없는 임시 건물이 반복적으로 확장되고 단순하고 값싼 소모성 건물의 공장 시스템이 탄생했다. \r\n");
      out.write("						1950년대 중반, 농촌 지역은 자금이 부족했고, 도시 지역이 넘쳐났고, 도시 스프롤 현상이 두드러지게 중요한 건물을 지을 돈이 거의 없이 시작되었다.<br><br>\r\n");
      out.write("\r\n");
      out.write("						&nbsp 돈과 수요가 허용하는 한 건물은 최대한 빨리 지어졌지만 그 안에 개인의 정체성은 없었다. \r\n");
      out.write("						건축가는 대부분 미국에서 훈련 받았으며, 지역 사회의 외관과 느낌에 크게 의지하지 않고 미국의 디자인, 관점, 방법을 가져 왔다. \r\n");
      out.write("						노동자의 주거 수요가 증가함에 따라 전통적인 한옥 마을은 파괴되고 수백 채의 단순한 값싼 아파트가 매우 빠르게 지어졌으며 도심 주변의 베드타운은 회사 주택으로 성장, 건설되었고 자금이 조달되었다. \r\n");
      out.write("						미적 감각을 보이려는 노력은 거의 없었다.<br><br>\r\n");
      out.write("\r\n");
      out.write("						&nbsp 단순한 고속 주택에 대한 이러한 절박함으로 인해 대부분의 한국 도심을 특색이 없는 상태로 만들었다. \r\n");
      out.write("						일과 생활을 위한 둔탁한 콘크리트 타워가 줄지어 늘어서 있고 값싼 자재로 재건된 지역 이웃으로 구성되어 있다. \r\n");
      out.write("						계획이 가능했다면 계획을 위한 시도가 거의 또는 전혀 이루어지지 않았다. 시골에서는 전통적인 건축이 계속되었다.<br><br>\r\n");
      out.write("\r\n");
      out.write("						&nbsp 1980년대까지만 해도, 한국에는 건축이 있었지만 전통 건물들을 포함한 건물들은 미적 감각이 부족하고 디자인 감각이 제한적이며 이웃이나 문화에 통합되지 않았다. \r\n");
      out.write("						한국이 스포츠 문화를 통해 세계로 진출하면서 기능성이 한계에 이르렀다는 인식이 빠르게 다가왔다. 스포츠 건축이 한국식으로 바뀌기 시작했다.<br><br>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </li>          \r\n");
      out.write("                <li>\r\n");
      out.write("                	<h3>현대 대중문화</h3>\r\n");
      out.write("                    <img src=\"assets/NationInfo/Korea/K10.jpg\" alt=\"문화적 특성 3\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                    	&nbsp K-pop(영어: Korean Popular Music, 케이팝)은 대한민국에서 대중적 인기를 얻는 유행 음악을 말한다. \r\n");
      out.write("						간단히 가요(歌謠)라고 부르기도 하며, 영미권의 대중음악을 팝(pop)이라고 부르고, 영미권 이외의 국가의 대중가요도 국가 이니셜을 붙여 나타내는 데서 K-POP이라고 쓴다. \r\n");
      out.write("						특히 대한민국 대중가요가 해외에서 인기를 얻게 된 이후에 K-pop이라는 명칭이 대한민국 이외 국가에서 대한민국 대중가요를 가리키는 이름으로 널리 사용된다. \r\n");
      out.write("						K-pop은 현재 한류로 인해 전세계에서 인기가 많아지고 있으며, 주로 아시아, 특히 동아시아 지방에서 인기를 끌고 있다. 주로 대만, 일본 등지에서 매우 인기가 높다.<br><br>\r\n");
      out.write("\r\n");
      out.write("						&nbsp 1992년에 데뷔한 서태지와 아이들로부터, H.O.T., 젝스키스, 신화, god 등 1세대 아이돌의 음악을 시작으로 일레트로닉 사운드와 힙합의 그 당시에는 \r\n");
      out.write("						다소 낯설면서 중독성 있는 노래들을 선보이며 K-pop의 문을 열었고 이후 2000년대 중반 대한민국의 2세대 아이돌 보이그룹과 걸 그룹들이 대한민국, 외국에서 큰 성공을 거둔 이후, \r\n");
      out.write("						K-pop이라는 단어를 이런 보이그룹과 걸그룹의 음악만으로 한정해서 정의하는 경향이 많아졌다. 과거에는 한국 음악 전반을 아우르는 느낌이었으나 최근에는 그냥 한국에서 만들어진 댄스음악, \r\n");
      out.write("						혹은 아이돌 음악 등을 일컫는 의미로 통용되고 있는 듯하다.<br><br>\r\n");
      out.write(" \r\n");
      out.write("						&nbsp 반면, 솔로 가수의 경우 넓은 의미의 K-pop 아티스트 범주에 들어가기도 하나, 이를 인정하지 아니하는 경우도 존재한다. \r\n");
      out.write("						예를 들면 아이유와 같은 솔로가수들에게 \"솔로 가수가 어떻게 k-pop 가수인가\" 등의 비판적 목소리가 존재한다.<br><br>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"right\">\r\n");
      out.write("        <h2>관광지</h2>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>서울 경복궁</h3>\r\n");
      out.write("            <img src=\"assets/NationInfo/Korea/K1.jpg\" alt=\"경복궁\">\r\n");
      out.write("            <p>경복궁은 조선 왕조의 법궁(法宮)으로, 1395년에 창건되었습니다. 서울의 중심부에 위치하며, 한국 전통 건축의 아름다움을 느낄 수 있는 곳입니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>부산 해운대</h3>\r\n");
      out.write("            <img src=\"assets/NationInfo/Korea/K2.jpg\" alt=\"부산 해운대\">\r\n");
      out.write("            <p>해운대는 부산을 대표하는 해변으로, 여름철 많은 관광객이 찾는 명소입니다. 해변 외에도 주변에 다양한 먹거리와 즐길 거리가 많습니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>제주도</h3>\r\n");
      out.write("            <img src=\"assets/NationInfo/Korea/K3.jpg\" alt=\"제주도\">\r\n");
      out.write("            <p>제주도는 한국의 대표적인 관광지로, 아름다운 자연경관과 독특한 문화로 유명합니다. 한라산, 성산일출봉, 그리고 다양한 해변을 즐길 수 있습니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>전주 한옥마을</h3>\r\n");
      out.write("            <img src=\"assets/NationInfo/Korea/K4.jpg\" alt=\"전주 한옥마을\">\r\n");
      out.write("            <p>전주 한옥마을은 전통 한옥 700여 채가 모여 있는 곳으로, 전통과 현대가 조화를 이루는 멋진 관광지입니다. 한복 체험, 전통 음식 맛보기, 전통 공예 체험 등이 가능합니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>경주 불국사</h3>\r\n");
      out.write("            <img src=\"assets/NationInfo/Korea/K5.jpg\" alt=\"경주 불국사\">\r\n");
      out.write("            <p>불국사는 신라 시대에 건립된 절로, 유네스코 세계문화유산으로 지정되어 있습니다. 석가탑과 다보탑 등 아름다운 석조물이 많으며, 한국 불교의 역사를 느낄 수 있는 곳입니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>설악산 국립공원</h3>\r\n");
      out.write("            <img src=\"assets/NationInfo/Korea/K6.jpg\" alt=\"설악산\">\r\n");
      out.write("            <p>설악산은 한국의 대표적인 국립공원으로, 아름다운 산세와 계곡, 다양한 동식물을 감상할 수 있습니다. 특히 가을 단풍이 유명하며, 등산객들에게 인기가 많습니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tourist-info\">\r\n");
      out.write("            <h3>담양 죽녹원</h3>\r\n");
      out.write("            <img src=\"assets/NationInfo/Korea/K7.jpg\" alt=\"담양 죽녹원\">\r\n");
      out.write("            <p>담양 죽녹원은 대나무 숲으로 유명한 관광지입니다. 푸른 대나무 숲 속을 산책하며 맑은 공기를 마실 수 있으며, 전통 한옥과 정자, 연못 등도 감상할 수 있습니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
