/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-17 12:54:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Project.View;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.sql.*;
import javabean.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Project/View/dbconn.jsp", Long.valueOf(1717966954391L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(5);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javabean");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>C&T: Trip And Culture</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/index.css\" type=\"text/css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/index.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");

request.setCharacterEncoding("utf-8");
	Connection conn = null;
	String url = "jdbc:mysql://127.0.0.1:3306/test";
	String user = "root";
	String password = "1234";
	Class.forName("com.mysql.cj.jdbc.Driver");
	conn = DriverManager.getConnection(url, user, password);

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("	\r\n");
      out.write("    \r\n");
      out.write("    ");

    	request.setCharacterEncoding("utf-8");
    	String uid = request.getParameter("id");
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <header>\r\n");
      out.write("        <h1><a href=\"index.jsp?id=");
      out.print(uid);
      out.write("\">CT: Culture&Trip</a></h1>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("            	<li><a href=\"Chatbot.jsp?id=");
      out.print(uid);
      out.write("\">여행관련 챗봇</a></li>\r\n");
      out.write("                <li><a href=\"NationalInfo/nationalinfo.jsp?id=");
      out.print(uid);
      out.write("\">나라 소개</a></li>\r\n");
      out.write("                <li><a href=\"https://stti.tripbuilder.co.kr/\">여행 성향 분석</a></li>\r\n");
      out.write("                <li><a href=\"tripcommunity.jsp?id=");
      out.print(uid);
      out.write("\">여행 후기 게시판</a></li>\r\n");
      out.write("                <li><a href=\"profile.jsp?id=");
      out.print(uid);
      out.write("\">프로필</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"section\" id=\"welcome-text\">\r\n");
      out.write("		<h1>어서오세요! <br>당신이 방문할 국가의 정보와<br>후기를 확인해보세요!</h1>\r\n");
      out.write("	</div>\r\n");
      out.write("    \r\n");
      out.write("	\r\n");
      out.write("		<div class=\"section odd\" id=\"section1\">\r\n");
      out.write("         	<div class=\"image-holder\">\r\n");
      out.write("      			<img src=\"../assets/trip1.jpg\" alt=\"[introduce]\">\r\n");
      out.write("    		</div>\r\n");
      out.write("    		<div class=\"text-holder\">\r\n");
      out.write("      			<h2>동아시아 국가들의 소재별 문화 정보</h2>\r\n");
      out.write("      			<p>안녕하세요! 저희 웹사이트에 오신 것을 환영합니다.<br>\r\n");
      out.write("      			동아시아는 오랜 역사와 독특한 문화를 지닌 지역으로, 각 나라마다 고유한 전통과 예술, 생활 방식을 자랑합니다.<br><br>\r\n");
      out.write("      			이곳은 한국, 중국, 일본 등 동아시아 국가들의 다양한 문화 정보를 소재별로 정리하여 제공하는 공간입니다.<br><br>\r\n");
      out.write("				저희 웹사이트에서는 각 나라의 음식, 의복, 전통 예술, 건축 양식, 축제 등 다양한 주제에 대해 심층적인 정보를 제공합니다.<br><br>\r\n");
      out.write("				각 나라의 문화적 배경과 역사적 맥락을 이해함으로써 동아시아의 다채로운 문화를 더 깊이 있게 체험할 수 있을 것입니다.<br><br>\r\n");
      out.write("				동아시아 문화에 관심이 있는 분들, 여행을 계획 중인 분들, 혹은 단순히 새로운 것을 배우고자 하는 분들 모두에게 유익한 정보를 제공하고자 합니다.<br><br>\r\n");
      out.write("				함께 동아시아의 아름다움과 다양성을 탐험해 보세요.\r\n");
      out.write("      			 </p>\r\n");
      out.write("    		</div>\r\n");
      out.write("    	</div>\r\n");
      out.write("    <div class=\"section even\" id=\"section2\">\r\n");
      out.write("        <div class=\"image-holder\">\r\n");
      out.write("      		<img src=\"../assets/trip2.jpg\" alt=\"[section2]\">\r\n");
      out.write("    	</div>\r\n");
      out.write("    	<div class=\"text-holder\">\r\n");
      out.write("      		<h2>여행 후기 게시판</h2>\r\n");
      out.write("      		<p>\r\n");
      out.write("      		저희 웹사이트는 여행을 사랑하는 많은 분들이 직접 경험한 동아시아 여행 후기를 공유하는 게시판을 운영하고 있습니다.<br><br>\r\n");
      out.write("      		이곳에서는 다양한 사람들이 실제로 방문한 장소, 체험한 문화, 만난 사람들에 대한 생생한 이야기를 읽어볼 수 있습니다.<br><br>\r\n");
      out.write("      		각기 다른 시선으로 바라본 동아시아의 모습을 통해 더욱 풍부하고 다채로운 정보를 얻을 수 있으며, 자신만의 여행 계획을 세우는 데 큰 도움이 될 것입니다.<br><br>\r\n");
      out.write("      		이곳에서 제공하는 자료들은 신뢰할 수 있는 출처를 바탕으로 하여 정확하고 풍부한 내용을 담고 있습니다.<br><br>\r\n");
      out.write("      		동아시아 문화에 관심이 있는 분들, 여행을 계획 중인 분들, 혹은 단순히 새로운 것을 배우고자 하는 분들 모두에게 유익한 정보를 제공하고자 합니다.<br><br>\r\n");
      out.write("			동아시아의 아름다움과 다양성을 탐험해 보세요.\r\n");
      out.write("			</p>\r\n");
      out.write("    	</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"section odd\" id=\"section3\">\r\n");
      out.write("        <div class=\"image-holder\">\r\n");
      out.write("      		<img src=\"../assets/ChatbotIMG2.jpg\" alt=\"[section3]\">\r\n");
      out.write("    	</div>\r\n");
      out.write("    	<div class=\"text-holder\">\r\n");
      out.write("      		<h2>여행 챗봇</h2>\r\n");
      out.write("      		<p>\r\n");
      out.write("      		저희 웹사이트는 GPT-3.5-turbo 기반의 챗봇 기능을 제공합니다.<br><br>\r\n");
      out.write("      		이 챗봇을 통해 여행과 연관된 정보를 검색하면 실시간으로 필요한 정보를 얻을 수 있습니다.<br><br> \r\n");
      out.write("      		챗봇은 동아시아 각국의 관광 명소, 맛집, 교통 정보 등 다양한 질문에 대해 빠르고 정확한 답변을 제공합니다.<br><br> \r\n");
      out.write("      		여행 계획을 세우거나 궁금한 점이 있을 때 언제든지 이용해보세요.<br><br>\r\n");
      out.write("      		</p>\r\n");
      out.write("    	</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("   \r\n");
      out.write("    <footer>\r\n");
      out.write("    	<div id=\"logo\">\r\n");
      out.write("    		<img src=\"../assets/Logo.png\" alt=\"LOGO\" id=\"Logoimg\">\r\n");
      out.write("    	</div>\r\n");
      out.write("  		<div>\r\n");
      out.write("  			CEO. 김대현 <br>\r\n");
      out.write("  			Addr. 서울특별시 금천구 가산1로 280-3 우림하이엔드타워 6차 14F \r\n");
      out.write("  			고객상담실 Fax/Tel: 02 - 223 -2912~5 <br>\r\n");
      out.write("  			COPYRIGHT 2024. C&T. ALL RIGHT RESERVED.\r\n");
      out.write("         </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
